version: '3.8'

services:
  app:
    image: fastapi-app:latest
    build:
      context: .
      dockerfile: Dockerfile-App
    environment:
      - DATABASE_URL=postgresql://user:password@host:port/database
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
