version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - retee

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - retee

networks:
  retee:

volumes:
  db_volume:
