version: '3.8'

services:
  db:
    container_name: db_container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - retee
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M' 

  flask:
    container_name: flask_container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - retee
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'

networks:
  retee:
    driver: bridge

volumes:
  db_volume:
